using System.Collections.Generic;

/// <summary>
/// Source copy for the Unity Localization "UI" string table.
/// The editor importer writes these entries into zh-Hans and en tables.
/// </summary>
public static class UiCopy
{
    public const int Revision = 1;

    public readonly struct Entry
    {
        public readonly string Key;
        public readonly string Zh;
        public readonly string En;

        public Entry(string key, string zh, string en)
        {
            Key = key;
            Zh = zh;
            En = en;
        }
    }

    public static readonly Entry[] All =
    {
        new Entry("title.branded", "{0} · {1}", "{0} · {1}"),

        new Entry("common.back", "返回", "Back"),
        new Entry("common.prev", "上一步", "Previous"),
        new Entry("common.next", "下一步", "Next"),
        new Entry("common.reset", "重置", "Reset"),
        new Entry("common.hint", "提示", "Hint"),
        new Entry("common.demo", "自动演示", "Auto Demo"),
        new Entry("common.lesson", "讲解", "Lesson"),
        new Entry("common.free", "自由实验", "Free Lab"),
        new Entry("common.challenge", "挑战", "Challenge"),
        new Entry("common.challengeMode", "挑战模式", "Challenge"),
        new Entry("common.done", "挑战完成", "Challenge complete"),
        new Entry("common.submit", "提交", "Submit"),
        new Entry("common.retryChallenge", "重新挑战", "Retry"),
        new Entry("common.tryAgain", "再试一次", "Try Again"),
        new Entry("common.mainMenu", "返回主菜单", "Main Menu"),
        new Entry("common.close", "关闭", "Close"),
        new Entry("common.quit", "退出", "Quit"),
        new Entry("common.settings", "设置", "Settings"),
        new Entry("common.language", "语言", "Language"),
        new Entry("common.on", "开", "On"),
        new Entry("common.off", "关", "Off"),
        new Entry("common.learnView", "学习", "Learn"),
        new Entry("common.select", "选择", "Select"),
        new Entry("common.correct", "回答正确！", "Correct!"),
        new Entry("common.finishQuestion", "请先完成当前挑战题", "Finish the current question first"),
        new Entry("common.demo.learnOnly", "自动演示在讲解关卡中播放", "Auto Demo plays in the lesson"),
        new Entry("common.demo.done", "自动演示结束。可以自己操作。自由实验和挑战从主菜单进入。", "Auto Demo is finished. You can try it yourself. Open Free Lab or Challenge from the main menu."),
        new Entry("common.lesson.menu", "讲解已完成。自由实验和挑战从主菜单进入。", "The lesson is finished. Open Free Lab or Challenge from the main menu."),
        new Entry("common.keys.lesson", "右键旋转视角    滚轮缩放    上一步 / 下一步    Esc 返回", "Right-drag to orbit    Scroll to zoom    Previous / Next    Esc to leave"),
        new Entry("quiz.again", " · 再想想", " · Not quite"),
        new Entry("quiz.title", "{0} · 挑战", "{0} · Challenge"),
        new Entry("quiz.scoring", "无提示、无答错通关得三星", "Three stars: no hints and no wrong answers"),

        new Entry("menu.eyebrow", "科学工作室", "Science Studio"),
        new Entry("menu.subtitle", "先理解原理，再动手实验，最后挑战三星。", "Learn the idea, try the experiment, then earn three stars."),
        new Entry("menu.netfold", "立体图形", "Solid Shapes"),
        new Entry("menu.netfold.blurb", "展开、三视图与截面", "Nets, views, and sections"),
        new Entry("menu.drift", "分子热运动", "Molecular Motion"),
        new Entry("menu.drift.blurb", "扩散、温度与微观粒子", "Diffusion, temperature, particles"),
        new Entry("menu.lens", "凸透镜成像", "Convex Lens"),
        new Entry("menu.lens.blurb", "物距、像距与光路", "Distance and ray diagrams"),
        new Entry("menu.progress", "探索进度  {0} / 9 星   ·   最佳成绩自动保存", "Progress  {0} / 9 stars   ·   best score saved"),
        new Entry("menu.hint", "右键旋转视角    滚轮缩放    WASD 平移    Esc 返回", "Right-drag to orbit    Scroll to zoom    WASD to move    Esc to leave"),
        new Entry("menu.waiting", "等待探索  ☆☆☆", "Not yet explored  ☆☆☆"),
        new Entry("menu.best", "最佳成绩  {0}", "Best  {0}"),
        new Entry("menu.settings.title", "设置", "Settings"),
        new Entry("menu.settings.language", "语言", "Language"),
        new Entry("menu.settings.hint", "选择界面语言。进入实验后会使用这里的语言。", "Choose a language. Labs use the language you pick here."),
        new Entry("menu.current.zh", "当前语言：中文", "Current language: 中文"),
        new Entry("menu.current.en", "当前语言：English", "Current language: English"),

        new Entry("tool.rotate", "旋转", "Rotate"),
        new Entry("tool.scale", "缩放", "Scale"),
        new Entry("tool.unfold", "展开", "Unfold"),
        new Entry("tool.fold", "折叠", "Fold"),
        new Entry("tool.views", "三视图", "Views"),
        new Entry("tool.section", "截面", "Section"),
        new Entry("tool.front", "主视投影", "Front"),
        new Entry("tool.top", "俯视投影", "Top"),
        new Entry("tool.side", "左视投影", "Side"),

        new Entry("view.section", "截面", "Section"),
        new Entry("view.challenge", "挑战", "Challenge"),
        new Entry("view.lesson", "讲解", "Lesson"),
        new Entry("view.rotate", "旋转", "Rotate"),
        new Entry("view.scale", "缩放", "Scale"),
        new Entry("view.select", "选择", "Select"),
        new Entry("view.net", "展开图", "Net"),
        new Entry("view.solid", "立体", "Solid"),
        new Entry("view.ortho", "三视图", "Three views"),
        new Entry("view.free", "自由实验", "Free Lab"),
        new Entry("view.learn", "学习", "Learn"),
        new Entry("viewname.front", "主视图", "Front"),
        new Entry("viewname.top", "俯视图", "Top"),
        new Entry("viewname.side", "左视图", "Left"),

        new Entry("shape.cube", "正方体", "Cube"),
        new Entry("shape.cylinder", "圆柱", "Cylinder"),
        new Entry("shape.cone", "圆锥", "Cone"),
        new Entry("shape.prism", "三棱柱", "Triangular prism"),
        new Entry("shape.triangle", "三角形", "Triangle"),
        new Entry("shape.rect", "矩形", "Rectangle"),
        new Entry("shape.para", "平行四边形", "Parallelogram"),
        new Entry("shape.hex", "六边形", "Hexagon"),
        new Entry("option.a", "选项 A", "Option A"),
        new Entry("option.b", "选项 B", "Option B"),
        new Entry("option.c", "选项 C", "Option C"),

        new Entry("netfold.free.body", "从顶部选择一个几何体。一次只显示一个，可以旋转、展开、看三视图，或拖动截面。", "Pick a solid from the top. Only one is shown. Rotate it, unfold it, open the three views, or drag the cutting plane."),
        new Entry("netfold.free.current", "当前是{0}。可以旋转、缩放、展开、折叠、看三视图，或拖动截面。换一个几何体时，上一个会收起来。", "This is a {0}. Rotate, scale, unfold, fold, open the three views, or drag the cutting plane. Choosing another solid puts this one away."),
        new Entry("netfold.lesson.done", "四步讲解已完成。自由实验和挑战从主菜单进入。", "The four-step lesson is finished. Open Free Lab or Challenge from the main menu."),
        new Entry("netfold.keys", "右键旋转视角    滚轮缩放    物体已锁定，只播放讲解动画    Esc 返回", "Right-drag to orbit    Scroll to zoom    The solid is locked while the lesson plays    Esc to leave"),
        new Entry("netfold.none", "未选择几何体", "No solid selected"),
        new Entry("netfold.faces", "面数  {0}", "Faces  {0}"),
        new Entry("netfold.faces.empty", "面数  --", "Faces  --"),
        new Entry("netfold.edges", "棱数  {0}", "Edges  {0}"),
        new Entry("netfold.edges.empty", "棱数  --", "Edges  --"),
        new Entry("netfold.verts", "顶点数  {0}", "Vertices  {0}"),
        new Entry("netfold.verts.empty", "顶点数  --", "Vertices  --"),
        new Entry("netfold.view", "当前视图  {0}", "View  {0}"),
        new Entry("netfold.section", "截面边数  {0}", "Section sides  {0}"),
        new Entry("netfold.section.empty", "截面边数  --", "Section sides  --"),
        new Entry("netfold.rays", "投影线  主{0}  俯{1}  左{2}", "Rays  Front {0}  Top {1}  Side {2}"),
        new Entry("netfold.rays.off", "投影线  关", "Rays  Off"),
        new Entry("netfold.step1.title", "步骤 1 / 4  认识正方体", "Step 1 / 4  Meet the cube"),
        new Entry("netfold.step2.title", "步骤 2 / 4  展开与折叠", "Step 2 / 4  Unfold and fold"),
        new Entry("netfold.step3.title", "步骤 3 / 4  三视图投影", "Step 3 / 4  Three-view projection"),
        new Entry("netfold.step4.title", "步骤 4 / 4  截面探究", "Step 4 / 4  Cross-sections"),
        new Entry("netfold.step1.body", "立体图形由面围成，面和面相交成棱，棱和棱相交成顶点。正方体有 6 个全等的正方形面、12 条棱、8 个顶点。相对的面互相平行，相邻的棱互相垂直。后面的展开、三视图和截面都会用到这些数量。", "A solid is enclosed by faces. Faces meet at edges, and edges meet at vertices. A cube has 6 identical square faces, 12 edges, and 8 vertices. Opposite faces are parallel, and neighboring edges are perpendicular. Nets, views, and sections all use these counts."),
        new Entry("netfold.step2.body", "沿着某些棱把立体剪开、铺平，得到的平面图形叫展开图。展开图必须能折回去，重新围成原来的立体。正方体一共有 11 种展开图。这些正方形要能折成封闭的盒子，面不能重叠，也不能缺一个面。", "Cut a solid along some edges and lay it flat. That flat shape is a net. A net must fold back into the original solid. A cube has 11 nets. The squares must form a closed box, with no overlap and no missing face."),
        new Entry("netfold.step3.body", "三视图是从三个方向看同一个立体：正面是主视图，上面是俯视图，左面是左视图。蓝色是主视方向，绿色是俯视方向，紫色是左视方向。主视图和俯视图一样长，叫长对正；主视图和左视图一样高，叫高平齐；俯视图和左视图一样宽，叫宽相等。画三视图时，三个图的位置和尺寸都要符合这三句话。", "Three views show one solid from three directions: the front view, the top view, and the left view. Blue is the front direction, green is the top, and purple is the left. Front and top share the same length, front and left share the same height, and top and left share the same width."),
        new Entry("netfold.step4.body", "用一个平面去截立体图形，平面和表面相交围成的图形叫截面。正方体的截面不一定是正方形。平面切得越斜，边数可以变多，截面可以是三角形、四边形、五边形，最多是六边形。右侧的截面边数会跟着切割角度变化。", "A plane cutting through a solid makes a cross-section. A cube's section is not always a square. A steeper cut can add sides: a triangle, quadrilateral, pentagon, or at most a hexagon. The side count on the right follows the cutting angle."),
        new Entry("netfold.q1.title", "第 1 题  根据三视图选择几何体", "Question 1  Choose the solid from the views"),
        new Entry("netfold.q1.body", "根据台上的三个视图，选择对应的几何体。", "Use the three views on the stage and choose the matching solid."),
        new Entry("netfold.q2.title", "第 2 题  根据几何体选择三视图", "Question 2  Choose the views for the solid"),
        new Entry("netfold.q2.body", "台上的几何体对应哪一组三视图？从左到右是 A、B、C。", "Which set of views matches the solid? From left to right: A, B, C."),
        new Entry("netfold.q3.title", "第 3 题  判断截面形状", "Question 3  Name the cross-section"),
        new Entry("netfold.q3.body", "斜切正方体得到的截面是哪一种？从左到右对应四个选项。", "Which shape is this slanted cut through a cube? The four choices run from left to right."),
        new Entry("netfold.hint1", "提示：三个视图都是正方形，只有正方体同时满足。", "Hint: all three views are squares, and only a cube matches."),
        new Entry("netfold.hint2", "提示：俯视图是三角形的，对应三棱柱。", "Hint: the top view is a triangle, so it is a triangular prism."),
        new Entry("netfold.hint3", "提示：对边平行且相等，但夹角不是直角，所以是平行四边形，不是矩形。", "Hint: opposite sides are parallel and equal, but the angles are not right angles, so it is a parallelogram, not a rectangle."),
        new Entry("netfold.wrong", "再想一想，错误的视图已用红色标出。", "Look again. The wrong view is marked in red."),

        new Entry("stars.3", "一次通过且未使用提示", "Cleared on the first try, with no hints"),
        new Entry("stars.2", "使用了 1 次提示", "Used 1 hint"),
        new Entry("stars.1.hints", "使用了 2 次以上提示或进行了重试", "Used 2 or more hints, or retried"),
        new Entry("stars.1.retry", "进行了重试", "Retried"),
        new Entry("stars.0", "尚未完成本关挑战", "This challenge is not finished"),
        new Entry("result.newBest", "新的最佳成绩！  {0}", "New best!  {0}"),
        new Entry("result.history", "历史最佳  {0}", "Best so far  {0}"),
        new Entry("knowledge.netfold", "知识卡\n正方体：6 面 12 棱 8 顶点\n圆柱：3 面 2 棱 0 顶点\n圆锥：2 面 1 棱 1 顶点\n三棱柱：5 面 9 棱 6 顶点\n斜切正方体可以得到三角形到六边形的截面。", "Notes\nCube: 6 faces, 12 edges, 8 vertices\nCylinder: 3 faces, 2 edges, 0 vertices\nCone: 2 faces, 1 edge, 1 vertex\nTriangular prism: 5 faces, 9 edges, 6 vertices\nA slanted cut through a cube can have 3 to 6 sides."),
        new Entry("knowledge.drift", "知识卡\n分子在不停地做无规则运动。\n温度越高，分子运动越剧烈，扩散越快。\n扩散是分子从高浓度向低浓度运动。\n分子之间有间隔，酒精与水混合后总体积小于两者之和。", "Notes\nMolecules never stop moving at random.\nHigher temperature means faster motion and faster diffusion.\nDiffusion carries molecules from high concentration toward low concentration.\nMolecules have gaps between them, so alcohol plus water occupies less volume than the two liquids apart."),
        new Entry("knowledge.lens", "知识卡\n凸透镜对光有会聚作用。\n1/f = 1/u + 1/v。\nu > 2f：倒立缩小实像。\nu = 2f：倒立等大实像。\nf < u < 2f：倒立放大实像。\nu = f：不成像。\nu < f：正立放大虚像。", "Notes\nA convex lens converges light.\n1/f = 1/u + 1/v.\nu > 2f: inverted, diminished real image.\nu = 2f: inverted, same-size real image.\nf < u < 2f: inverted, magnified real image.\nu = f: no image.\nu < f: upright, magnified virtual image."),

        new Entry("drift.sub", "分子热运动与扩散", "Molecular motion and diffusion"),
        new Entry("drift.free.body", "可切换微观、调节温度、把品红滴进冷水或热水，也可以把酒精烧杯拖进水里。", "Switch to the micro view, change the temperature, drop fuchsin into cold or hot water, or drag the alcohol beaker into the water."),
        new Entry("drift.keys.free", "右键旋转  滚轮缩放  WASD平移  Tab微观  R重置  Enter确认  Esc返回", "Right-drag orbit  Scroll zoom  WASD move  Tab micro  R reset  Enter confirm  Esc leave"),
        new Entry("drift.curveKey", "青线温度    橙线扩散进度", "Cyan: temperature    Orange: spread"),
        new Entry("drift.tempCap", "温度", "Temperature"),
        new Entry("drift.heat", "加热", "Heat"),
        new Entry("drift.cool", "冷却", "Cool"),
        new Entry("drift.drop", "滴入品红", "Add fuchsin"),
        new Entry("drift.gas", "打开气体瓶", "Open gas"),
        new Entry("drift.run", "开始扩散", "Start diffusion"),
        new Entry("drift.ion", "开始电解", "Start electrolysis"),
        new Entry("drift.tool.view", "宏观/微观", "Micro/Macro"),
        new Entry("drift.tool.heat", "浓度热力图", "Heatmap"),
        new Entry("drift.tool.curve", "温度曲线", "Temp curve"),
        new Entry("drift.micro", "微观", "Micro"),
        new Entry("drift.macro", "宏观", "Macro"),
        new Entry("drift.count", "分子数  {0}", "Molecules  {0}"),
        new Entry("drift.stateLine", "当前状态  {0} · {1}", "Status  {0} · {1}"),
        new Entry("drift.volume", "滴加体积  {0}%", "Drop volume  {0}%"),
        new Entry("drift.temp.empty", "温度  --", "Temperature  --"),
        new Entry("drift.temp.value", "温度  {0}  {1} ℃", "Temperature  {0}  {1} °C"),
        new Entry("drift.speed", "粒子平均速度  {0}  （相对）", "Mean particle speed  {0}  (relative)"),
        new Entry("drift.time.empty", "扩散时间  --", "Diffusion time  --"),
        new Entry("drift.time", "扩散时间  {0} 秒", "Diffusion time  {0} s"),
        new Entry("drift.time.even", "扩散时间  {0} 秒  已均匀", "Diffusion time  {0} s  even"),
        new Entry("drift.time.going", "扩散时间  {0} 秒  扩散中", "Diffusion time  {0} s  spreading"),
        new Entry("drift.conc.mix", "浓度分布  50+50=100 mL，实际 92 mL", "Concentration  50+50=100 mL, actual 92 mL"),
        new Entry("drift.conc.separate", "浓度分布  水 50 mL，酒精 50 mL", "Concentration  water 50 mL, alcohol 50 mL"),
        new Entry("drift.conc.none", "浓度分布  尚无品红", "Concentration  no fuchsin yet"),
        new Entry("drift.conc.heat", "浓度分布  {0}", "Concentration  {0}"),
        new Entry("drift.conc.progress", "浓度分布  扩散进度 {0}%", "Concentration  spread {0}%"),
        new Entry("drift.heat.none", "尚无品红", "No fuchsin yet"),
        new Entry("drift.heat.describe", "中心 {0}%    边缘 {1}%", "Center {0}%    Edge {1}%"),
        new Entry("drift.speed.empty", "粒子平均速度  --", "Mean particle speed  --"),
        new Entry("drift.conc.empty", "浓度分布  --", "Concentration  --"),
        new Entry("drift.state.empty", "当前状态  --", "Status  --"),
        new Entry("beaker.cold", "冷水", "Cold water"),
        new Entry("beaker.hot", "热水", "Hot water"),
        new Entry("beaker.alcohol", "酒精", "Alcohol"),
        new Entry("beaker.water", "水", "Water"),
        new Entry("band.fast", "很快", "Fast"),
        new Entry("band.mid", "中等", "Medium"),
        new Entry("band.slow", "很慢", "Slow"),
        new Entry("band.faster", "加快", "speeds up"),
        new Entry("band.slower", "减慢", "slows down"),
        new Entry("world.dropper", "品红滴管", "Fuchsin dropper"),
        new Entry("world.heat", "加热台", "Hot plate"),
        new Entry("world.cool", "冷却台", "Cold plate"),
        new Entry("world.thermo", "温度计", "Thermometer"),
        new Entry("world.ammonia", "氨水", "Ammonia"),
        new Entry("world.papers", "酚酞试纸", "Phenolphthalein paper"),
        new Entry("world.no2", "二氧化氮", "Nitrogen dioxide"),
        new Entry("world.cover", "玻璃罩", "Bell jar"),

        new Entry("drift.state.random", "分子在不停做无规则运动", "Molecules keep moving at random"),
        new Entry("drift.state.free", "可以自由调节温度、观察扩散，或把酒精拖进水里", "Change the temperature, watch diffusion, or drag the alcohol into the water"),
        new Entry("drift.lesson.done.title", "讲解完成", "Lesson complete"),
        new Entry("drift.lesson.done.body", "五步讲解已完成。想自己调节温度、滴品红或混合酒精，从主菜单进入自由实验。", "The five-step lesson is finished. To change the temperature, add fuchsin, or mix alcohol yourself, open Free Lab from the main menu."),
        new Entry("drift.heat.on", "浓度热力图已打开，红色高、蓝色低", "Heatmap on: red is high, blue is low"),
        new Entry("drift.heat.off", "浓度热力图已关闭", "Heatmap off"),
        new Entry("drift.hotter", "温度越高，分子运动越剧烈", "Higher temperature means faster molecular motion"),
        new Entry("drift.challenge.follow", "挑战中请按题目操作", "Follow the question during the challenge"),
        new Entry("drift.drop.step", "请进入步骤 3，再滴入品红", "Go to step 3, then add fuchsin"),
        new Entry("drift.answer.current", "请按当前题目作答", "Answer the current question"),
        new Entry("drift.gas.step", "请在步骤 3 打开气体瓶，观察氨分子和二氧化氮扩散", "In step 3, open the gas bottles and watch ammonia and nitrogen dioxide diffuse"),
        new Entry("drift.ammonia", "氨分子扩散，酚酞试纸由近及远变红", "Ammonia diffuses. The phenolphthalein paper turns red from near to far"),
        new Entry("drift.no2", "二氧化氮气体正在扩散", "Nitrogen dioxide is diffusing"),
        new Entry("drift.ion.state", "示意：带电微粒在电场中定向移动", "Illustration: charged particles drift in an electric field"),
        new Entry("drift.macro.still", "宏观下，水面看起来是静止的", "At the macro scale, the water looks still"),
        new Entry("drift.micro.move", "微观下，水分子在不停运动", "At the micro scale, water molecules never stop moving"),
        new Entry("drift.random.turn", "分子没有固定方向，碰撞后就转向", "Molecules have no fixed path. A collision sends them another way"),
        new Entry("drift.cold.hot", "冷水分子慢，热水分子快", "Molecules are slow in cold water and fast in hot water"),
        new Entry("drift.temp.up", "温度升高，分子运动加快", "As temperature rises, molecules move faster"),
        new Entry("drift.hot.faster", "热水中的品红扩散更快", "Fuchsin spreads faster in hot water"),
        new Entry("drift.volumes", "50 mL 水 + 50 mL 酒精", "50 mL water + 50 mL alcohol"),
        new Entry("drift.gaps.fill", "分子进入彼此的间隔，总体积变小", "Molecules slip into each other's gaps, so the total volume shrinks"),
        new Entry("drift.beat1.title", "步骤 1 / 5    宏观和微观", "Step 1 / 5    Macro and micro"),
        new Entry("drift.beat2.title", "步骤 2 / 5    无规则运动", "Step 2 / 5    Random motion"),
        new Entry("drift.beat3.title", "步骤 3 / 5    温度的影响", "Step 3 / 5    Effect of temperature"),
        new Entry("drift.beat4.title", "步骤 4 / 5    扩散", "Step 4 / 5    Diffusion"),
        new Entry("drift.beat5.title", "步骤 5 / 5    分子间的间隔", "Step 5 / 5    Gaps between molecules"),
        new Entry("drift.beat1.body", "一杯水放在桌上，水面平静，好像没有变化。水其实由大量分子组成，分子非常小，肉眼看不见。切到微观以后，就能看见这些分子在运动。宏观现象和微观粒子是同一杯水的两个层次。", "A beaker of water sits still, as if nothing is happening. Water is made of vast numbers of molecules, too small to see. Switch to the micro view and those molecules are moving. The calm surface and the moving particles are two scales of the same water."),
        new Entry("drift.beat2.body", "分子在不停地做无规则运动：没有固定路线，碰到别的分子就改变方向。只要不是绝对零度，这种运动就不会停。扩散、蒸发、溶解，都和分子的运动有关。", "Molecules move at random. They have no fixed route, and a collision changes their direction. This motion does not stop unless the temperature is absolute zero. Diffusion, evaporation, and dissolving all come from it."),
        new Entry("drift.beat3.body", "温度反映分子的平均动能。冷水里分子运动慢，热水里分子运动快。把热水继续加热，温度计上升，粒子速度和曲线也一起变快。所以同样的变化，在热水里总是比冷水更快。", "Temperature measures the average kinetic energy of the molecules. They move slowly in cold water and quickly in hot water. Heat the hot water further and the thermometer, the particle speed, and the curve all rise together. The same change is always faster in hot water."),
        new Entry("drift.beat4.body", "扩散是不同物质的分子彼此进入对方，方向是从浓度高的地方到浓度低的地方。品红同时滴进冷水和热水：热水中分子运动更剧烈，品红散得更快，先变得均匀。热力图里红色浓度高，蓝色浓度低。", "In diffusion, molecules of one substance move into another, from high concentration toward low concentration. Drop fuchsin into cold and hot water together: the hotter molecules move more, so the color evens out sooner. On the heatmap, red is high and blue is low."),
        new Entry("drift.beat5.body", "分子并不是紧紧挤在一起，中间有空隙。50 mL 水加上 50 mL 酒精，如果没有间隔，混合后应是 100 mL。实际大约只有 92 mL，因为两种分子钻进了彼此的空隙。", "Molecules are not packed solid. There are gaps between them. 50 mL of water plus 50 mL of alcohol would be 100 mL if there were no gaps. The mixture is only about 92 mL, because each kind of molecule slips into the other's gaps."),
        new Entry("drift.ui1.title", "步骤 1 / 4    认识分子运动", "Step 1 / 4    Molecular motion"),
        new Entry("drift.ui2.title", "步骤 2 / 4    温度对分子运动的影响", "Step 2 / 4    Temperature and motion"),
        new Entry("drift.ui3.title", "步骤 3 / 4    品红扩散实验", "Step 3 / 4    Fuchsin diffusion"),
        new Entry("drift.ui4.title", "步骤 4 / 4    分子间有间隔", "Step 4 / 4    Gaps between molecules"),
        new Entry("drift.ui1.body", "按 Tab 切换微观视图，观察烧杯里的水分子不停运动。", "Press Tab for the micro view and watch the water molecules keep moving."),
        new Entry("drift.ui2.body", "拖动温度滑块。温度升高时分子运动加快，温度计和速度曲线一起变化。", "Drag the temperature slider. As it rises, molecules speed up, and the thermometer and speed curve change with it."),
        new Entry("drift.ui3.body", "把品红滴管拖到冷水或热水烧杯上松开。可打开热力图，对比扩散快慢。", "Drag the fuchsin dropper onto the cold or hot beaker and release. Open the heatmap to compare how fast the color spreads."),
        new Entry("drift.ui4.body", "把酒精烧杯拖到水烧杯上。混合后总体积小于两者之和。", "Drag the alcohol beaker onto the water. After mixing, the volume is less than the two amounts added together."),
        new Entry("drift.gaps.short", "分子之间有间隔", "There are gaps between molecules"),
        new Entry("drift.spread.short", "品红从高浓度区域向低浓度区域扩散", "Fuchsin spreads from high concentration toward low concentration"),
        new Entry("drift.watch.which", "观察哪一杯品红扩散更快", "Watch which beaker the fuchsin colors faster"),
        new Entry("drift.choice.cold", "冷水扩散更快", "Cold water spreads faster"),
        new Entry("drift.choice.hot", "热水扩散更快", "Hot water spreads faster"),
        new Entry("drift.q2.predict", "预测 {0} ℃ 下的扩散快慢", "Predict how fast it spreads at {0} °C"),
        new Entry("drift.q3.adjust", "调节温度，使均匀时间落在 5.5–8.5 秒", "Set the temperature so the color evens out in 5.5–8.5 s"),
        new Entry("drift.q1.hotter", "温度越高，扩散越快", "The higher the temperature, the faster the diffusion"),
        new Entry("drift.q1.correct", "正确。热水中分子运动更剧烈，颜色会更快变均匀", "Correct. Molecules move more in hot water, so the color evens out sooner"),
        new Entry("drift.q2.again", "再看温度：高温很快，低温很慢", "Look at the temperature again: high is fast, low is slow"),
        new Entry("drift.q2.ok", "预测正确，正在播放扩散。预期「{0}」", "Correct. Playing the diffusion. Expected “{0}”."),
        new Entry("drift.started", "扩散已开始，请等待溶液均匀", "Diffusion has started. Wait until the solution is even"),
        new Entry("drift.uniform", "{0}已扩散均匀", "{0} is evenly mixed"),
        new Entry("drift.q2.measured", "实测 {0} 秒，与「{1}」相符", "Measured {0} s, matching “{1}”"),
        new Entry("drift.mixed", "分子之间有间隔。50 mL + 50 mL = 100 mL，混合后只有 92 mL", "Molecules have gaps between them. 50 mL + 50 mL = 100 mL, but the mixture is only 92 mL"),
        new Entry("drift.dropping", "{0}中，品红正在从高浓度向低浓度扩散", "In the {0}, fuchsin is spreading from high concentration toward low"),
        new Entry("drift.temp.locked", "扩散进行中，温度已锁定", "Diffusion is running, so the temperature is locked"),
        new Entry("drift.temp.given", "本题水温已给定", "This question already sets the water temperature"),
        new Entry("drift.nudge", "{0} {1} ℃，分子运动{2}", "{0} {1} °C, molecular motion {2}"),
        new Entry("drift.q.time.ok", "扩散时间 {0} 秒，落在目标范围内", "Diffusion time {0} s, inside the target range"),
        new Entry("drift.q.time.cold", "温度偏低，分子运动太慢", "Too cold: the molecules are moving too slowly"),
        new Entry("drift.q.time.hot", "温度偏高，分子运动太快", "Too hot: the molecules are moving too quickly"),
        new Entry("drift.hint1", "比较两杯变色速度。温度越高，扩散越快。", "Compare how fast the two beakers change color. Higher temperature means faster diffusion."),
        new Entry("drift.hint2", "水温很高选很快，中等水温选中等，接近冰水选很慢。", "Very hot water is Fast, medium water is Medium, and near-freezing water is Slow."),
        new Entry("drift.hint3", "目标是 5.5–8.5 秒。大约 45℃ 到 65℃ 会落在这个范围。", "The target is 5.5–8.5 seconds. About 45 °C to 65 °C lands in that range."),
        new Entry("drift.q1.title", "挑战 1 / 3    温度与扩散速度", "Challenge 1 / 3    Temperature and speed"),
        new Entry("drift.q2.title", "挑战 2 / 3    预测扩散时间", "Challenge 2 / 3    Predict the time"),
        new Entry("drift.q3.title", "挑战 3 / 3    调温达标", "Challenge 3 / 3    Hit the time"),
        new Entry("drift.q1.body", "冷水和热水已同时滴入品红。选出扩散更快的烧杯。", "Fuchsin was added to cold and hot water at the same time. Choose the beaker that spreads faster."),
        new Entry("drift.q2.body", "当前水温 {0} ℃。预测品红扩散到均匀的快慢。", "The water is {0} °C. Predict how fast the fuchsin becomes even."),
        new Entry("drift.q3.body", "调节温度，使品红在 5.5–8.5 秒内扩散均匀，然后开始扩散。", "Set the temperature so the fuchsin evens out in 5.5–8.5 seconds, then start diffusion."),

        new Entry("lens.sub", "凸透镜成像规律", "How a convex lens forms an image"),
        new Entry("lens.free.body", "拖动蜡烛、光屏和焦距，观察物距、像距和像的性质。", "Drag the candle, the screen, and the focal length. Watch the object distance, image distance, and the kind of image."),
        new Entry("lens.keys.challenge", "拖动蜡烛和光屏    L 光路    Tab 景深    R 重置    Esc 返回", "Drag the candle and screen    L rays    Tab depth    R reset    Esc leave"),
        new Entry("lens.keys.free", "拖动蜡烛和光屏    L 光路    R 重置    Esc 返回", "Drag the candle and screen    L rays    R reset    Esc leave"),
        new Entry("lens.u", "物距 u  {0}", "Object distance u  {0}"),
        new Entry("lens.v", "像距 v  {0}", "Image distance v  {0}"),
        new Entry("lens.f", "焦距 f  {0}", "Focal length f  {0}"),
        new Entry("lens.mag", "放大率  {0}", "Magnification  {0}"),
        new Entry("lens.nature.row", "像的性质  {0}", "Image  {0}"),
        new Entry("lens.rule.row", "当前规律  {0}", "Rule  {0}"),
        new Entry("lens.u.empty", "物距 u  —", "Object distance u  —"),
        new Entry("lens.v.empty", "像距 v  —", "Image distance v  —"),
        new Entry("lens.f.empty", "焦距 f  —", "Focal length f  —"),
        new Entry("lens.mag.empty", "放大率  —", "Magnification  —"),
        new Entry("lens.nature.empty", "像的性质  —", "Image  —"),
        new Entry("lens.rule.empty", "当前规律  —", "Rule  —"),
        new Entry("lens.fcap", "焦距 f（cm）", "Focal length f (cm)"),
        new Entry("lens.lamp", "光源开关", "Lamp"),
        new Entry("lens.ray1", "平行光线", "Parallel ray"),
        new Entry("lens.ray2", "过光心", "Through center"),
        new Entry("lens.ray3", "过焦点", "Through focus"),
        new Entry("lens.tool.rays", "显示光路", "Show rays"),
        new Entry("lens.tool.guides", "辅助线", "Guides"),
        new Entry("lens.tool.dof", "景深", "Depth"),
        new Entry("lens.noImage", "不成像", "No image"),
        new Entry("lens.inverted", "倒立", "Inverted"),
        new Entry("lens.upright", "正立", "Upright"),
        new Entry("lens.equal", "等大", "same-size"),
        new Entry("lens.magnified", "放大", "magnified"),
        new Entry("lens.reduced", "缩小", "diminished"),
        new Entry("lens.real", "实像", "real image"),
        new Entry("lens.virtual", "虚像", "virtual image"),
        new Entry("lens.nature", "{0}{1}{2}", "{0}, {1} {2}"),
        new Entry("lens.rule.focus", "u = f，折射光线平行射出，不成像", "u = f: refracted rays stay parallel, so no image forms"),
        new Entry("lens.rule.inside", "u < f，成正立放大虚像", "u < f: upright, magnified virtual image"),
        new Entry("lens.rule.beyond", "u > 2f，成倒立缩小实像", "u > 2f: inverted, diminished real image"),
        new Entry("lens.rule.twice", "u = 2f，成倒立等大实像", "u = 2f: inverted, same-size real image"),
        new Entry("lens.rule.between", "f < u < 2f，成倒立放大实像", "f < u < 2f: inverted, magnified real image"),
        new Entry("lens.choice.reduced", "倒立缩小实像", "Inverted, diminished real image"),
        new Entry("lens.choice.equal", "倒立等大实像", "Inverted, same-size real image"),
        new Entry("lens.choice.magnified", "倒立放大实像", "Inverted, magnified real image"),
        new Entry("lens.choice.virtual", "正立放大虚像", "Upright, magnified virtual image"),
        new Entry("lens.converge", "凸透镜对光有会聚作用", "A convex lens converges light"),
        new Entry("lens.focal.stronger", "焦距越小，会聚能力越强", "A shorter focal length converges light more strongly"),
        new Entry("lens.light.on", "光源已打开", "Lamp on"),
        new Entry("lens.light.off", "光源已关闭", "Lamp off"),
        new Entry("lens.rays.on", "三条特殊光线已显示", "The three special rays are shown"),
        new Entry("lens.rays.off", "光路已隐藏", "Rays hidden"),
        new Entry("lens.guides.on", "焦点辅助线已显示", "Focus guides shown"),
        new Entry("lens.guides.off", "辅助线已隐藏", "Guides hidden"),
        new Entry("lens.dof.on", "景深模糊已打开", "Depth-of-field blur on"),
        new Entry("lens.dof.off", "景深模糊已关闭", "Depth-of-field blur off"),
        new Entry("lens.rays.each", "可以单独观察每一条特殊光线", "You can inspect each special ray on its own"),
        new Entry("lens.lesson.done.title", "讲解完成", "Lesson complete"),
        new Entry("lens.lesson.done.body", "八步讲解已完成。想自己拖动蜡烛和光屏，从主菜单进入自由实验。", "The eight-step lesson is finished. To drag the candle and screen yourself, open Free Lab from the main menu."),
        new Entry("lens.focusing", "光屏正在移向清晰的实像", "The screen is moving toward a sharp real image"),
        new Entry("lens.ray.red", "红：平行于主光轴，折射后过焦点", "Red: parallel to the axis, then through the focus"),
        new Entry("lens.ray.green", "绿：通过光心，方向不变", "Green: through the optical center, direction unchanged"),
        new Entry("lens.ray.blue", "蓝：通过焦点，折射后平行于主光轴", "Blue: through the focus, then parallel to the axis"),
        new Entry("lens.case.beyond", "u > 2f，倒立缩小的实像", "u > 2f, inverted diminished real image"),
        new Entry("lens.case.twice", "u = 2f，倒立等大的实像", "u = 2f, inverted same-size real image"),
        new Entry("lens.case.between", "f < u < 2f，倒立放大的实像", "f < u < 2f, inverted magnified real image"),
        new Entry("lens.case.focus", "u = f，折射光线平行，不成像", "u = f, refracted rays are parallel, no image"),
        new Entry("lens.case.inside", "u < f，正立放大的虚像", "u < f, upright magnified virtual image"),
        new Entry("lens.focal.shrink", "焦距变小，会聚更强", "Focal length is decreasing, so the lens converges more"),
        new Entry("lens.beat1.title", "步骤 1 / 8    认识光具座", "Step 1 / 8    The optical bench"),
        new Entry("lens.beat2.title", "步骤 2 / 8    三条特殊光线", "Step 2 / 8    Three special rays"),
        new Entry("lens.beat3.title", "步骤 3 / 8    二倍焦距以外", "Step 3 / 8    Beyond 2f"),
        new Entry("lens.beat4.title", "步骤 4 / 8    二倍焦距处", "Step 4 / 8    At 2f"),
        new Entry("lens.beat5.title", "步骤 5 / 8    一倍与二倍之间", "Step 5 / 8    Between f and 2f"),
        new Entry("lens.beat6.title", "步骤 6 / 8    焦点上", "Step 6 / 8    At the focus"),
        new Entry("lens.beat7.title", "步骤 7 / 8    焦点以内", "Step 7 / 8    Inside the focus"),
        new Entry("lens.beat8.title", "步骤 8 / 8    焦距的影响", "Step 8 / 8    Changing the focal length"),
        new Entry("lens.beat1.body", "光具座上有蜡烛、凸透镜和光屏。蜡烛是物体，凸透镜把光会聚起来，光屏承接实像。物距 u 是物体到透镜的距离，像距 v 是像到透镜的距离，焦距 f 是焦点到透镜的距离。三者满足 1/f = 1/u + 1/v。光屏对准像时，实像最清晰。", "The bench holds a candle, a convex lens, and a screen. The candle is the object, the lens converges the light, and the screen catches the real image. Object distance u, image distance v, and focal length f satisfy 1/f = 1/u + 1/v. The real image is sharpest when the screen is at the image."),
        new Entry("lens.beat2.body", "凸透镜对光有会聚作用。平行于主光轴的光线，折射后通过焦点。通过光心的光线方向不变。通过焦点的光线，折射后平行于主光轴。任意两条特殊光线的交点，就是像的位置。", "A convex lens converges light. A ray parallel to the axis passes through the focus after refraction. A ray through the optical center does not change direction. A ray through the focus leaves parallel to the axis. The image is where any two of these rays meet."),
        new Entry("lens.beat3.body", "物体在二倍焦距以外（u > 2f）时，成倒立、缩小的实像。像在透镜另一侧，落在一倍焦距和二倍焦距之间。照相机就是这样：远处的景物，在底片上成缩小的实像。", "When the object is beyond twice the focal length (u > 2f), the image is real, inverted, and diminished. It falls on the other side of the lens, between f and 2f. A camera works this way: a distant scene becomes a smaller real image."),
        new Entry("lens.beat4.body", "物体正好在二倍焦距处（u = 2f）时，成倒立、等大的实像。像也在另一侧的二倍焦距处，物距和像距相等，放大率是 1。", "When the object is exactly at 2f, the image is real, inverted, and the same size. It also sits at 2f on the other side. Object and image distances are equal, and the magnification is 1."),
        new Entry("lens.beat5.body", "物体在一倍焦距和二倍焦距之间（f < u < 2f）时，成倒立、放大的实像。像在二倍焦距以外。投影仪、幻灯机利用的就是这种放大的实像。", "When the object is between f and 2f, the image is real, inverted, and magnified. It forms beyond 2f. Projectors use this magnified real image."),
        new Entry("lens.beat6.body", "物体放在焦点上（u = f）时，折射光线互相平行，不能相交，所以不成像。光屏移到任何位置，都得不到清晰的像。", "When the object is at the focus (u = f), the refracted rays are parallel and never meet, so no image forms. No screen position gives a sharp image."),
        new Entry("lens.beat7.body", "物体放在焦点以内（u < f）时，折射光线是发散的。把它们反向延长，会在物体同侧相交，成正立、放大的虚像。虚像不能呈在光屏上，要透过透镜用眼睛看。放大镜就是这样工作的。", "When the object is inside the focus (u < f), the refracted rays diverge. Extended backward, they meet on the object's side as an upright, magnified virtual image. A virtual image cannot be caught on a screen; you see it by looking through the lens. A magnifying glass works this way."),
        new Entry("lens.beat8.body", "焦距 f 越小，凸透镜的会聚能力越强。物体位置不变时，焦距调小，像会更靠近透镜，大小也会跟着变。焦距越大，会聚能力越弱。", "The smaller the focal length, the more strongly a convex lens converges light. With the object fixed, a shorter focal length pulls the image closer to the lens and changes its size. A longer focal length converges light more weakly."),
        new Entry("lens.ui1.title", "步骤 1 / 4    认识光具座", "Step 1 / 4    The optical bench"),
        new Entry("lens.ui2.title", "步骤 2 / 4    三条特殊光线", "Step 2 / 4    Three special rays"),
        new Entry("lens.ui3.title", "步骤 3 / 4    物距与成像规律", "Step 3 / 4    Object distance and the image"),
        new Entry("lens.ui4.title", "步骤 4 / 4    焦距的影响", "Step 4 / 4    Focal length"),
        new Entry("lens.ui1.body", "拖动蜡烛和光屏。凸透镜对光有会聚作用。右侧可看到 u、v、f。", "Drag the candle and the screen. A convex lens converges light. u, v, and f are shown on the right."),
        new Entry("lens.ui2.body", "红色平行于主光轴后过焦点，绿色过光心方向不变，蓝色过焦点后平行于主光轴。", "Red runs parallel to the axis and then through the focus. Green goes through the center and does not bend. Blue goes through the focus and then runs parallel to the axis."),
        new Entry("lens.ui3.body", "把蜡烛从远处拖向透镜。光屏会自动对焦，观察实像、不成像和虚像。", "Drag the candle in from far away. The screen focuses itself. Watch the real image, the missing image, and the virtual image."),
        new Entry("lens.ui4.body", "拖动焦距滑块。焦距越小，会聚能力越强，像距和像的大小都会变。", "Drag the focal-length slider. A shorter focal length converges more strongly, and both the image distance and the image size change."),
        new Entry("lens.watch.rays", "观察三条特殊光线如何汇聚", "Watch how the three special rays meet"),
        new Entry("lens.drag.candle", "把蜡烛从远处拖向凸透镜", "Drag the candle in toward the lens"),
        new Entry("lens.free.status", "自由调节蜡烛、焦距和光屏", "Move the candle, focal length, and screen freely"),
        new Entry("lens.drag.changing", "物距减小，像的性质在变化", "As the object distance falls, the image changes"),
        new Entry("lens.drag.virtual", "u < f，成正立放大虚像", "u < f: an upright, magnified virtual image"),
        new Entry("lens.near.sharp", "光屏接近清晰位置", "The screen is close to the sharp position"),
        new Entry("lens.sharp", "光屏上出现清晰的倒立实像", "A sharp inverted real image is on the screen"),
        new Entry("lens.blur", "光屏位置不对，像不清晰", "The screen is in the wrong place, so the image is blurry"),
        new Entry("lens.hint.v", "清晰位置 v = uf/(u-f)，约 {0}", "Sharp position v = uf/(u-f), about {0}"),
        new Entry("lens.hint.rule", "提示：{0}", "Hint: {0}"),
        new Entry("lens.hint.calc", "1/v = 1/f - 1/u，v = uf/(u-f) ≈ {0} cm", "1/v = 1/f - 1/u, so v = uf/(u-f) ≈ {0} cm"),
        new Entry("lens.need.number", "请输入像距，单位是厘米", "Enter the image distance in centimeters"),
        new Entry("lens.calc.ok", "计算正确，v = {0} cm", "Correct, v = {0} cm"),
        new Entry("lens.calc.again", "再算一次。公式：1/f = 1/u + 1/v，即 v = uf/(u-f)", "Try the calculation again. 1/f = 1/u + 1/v, so v = uf/(u-f)"),
        new Entry("lens.correct.nature", "正确：{0}", "Correct: {0}"),
        new Entry("lens.wrong.rule", "不对。{0}", "Not quite. {0}"),
        new Entry("lens.q1.title", "挑战 1 / 3    找清晰像", "Challenge 1 / 3    Find the sharp image"),
        new Entry("lens.q1.body", "拖动光屏，让倒立实像变清晰。", "Drag the screen until the inverted real image is sharp."),
        new Entry("lens.q1.status", "拖动光屏，直到像清晰", "Drag the screen until the image is sharp"),
        new Entry("lens.q2.title", "挑战 2 / 3    判断像的性质", "Challenge 2 / 3    Name the image"),
        new Entry("lens.q2.body", "根据物距和焦距选择像的性质。", "Use the object distance and focal length to choose the kind of image."),
        new Entry("lens.q2.status", "u = 22 cm，f = 15 cm", "u = 22 cm, f = 15 cm"),
        new Entry("lens.q3.title", "挑战 3 / 3    计算像距", "Challenge 3 / 3    Calculate the image distance"),
        new Entry("lens.q3.body", "u = 40 cm，f = 16 cm。求像距 v（厘米），回车提交。", "u = 40 cm, f = 16 cm. Find the image distance v in centimeters, then press Enter."),
        new Entry("lens.q3.status", "输入 v 的厘米数", "Enter v in centimeters"),
    };

    static Dictionary<string, Entry> _map;

    public static string Fallback(string key, bool english)
    {
        if (_map == null)
        {
            _map = new Dictionary<string, Entry>(All.Length);
            for (int i = 0; i < All.Length; i++)
            {
                _map[All[i].Key] = All[i];
            }
        }

        if (key != null && _map.TryGetValue(key, out Entry entry))
        {
            return english ? entry.En : entry.Zh;
        }

        return key ?? string.Empty;
    }
}
